name = "live"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "live.hey.xyz", custom_domain = true }
]

[placement]
mode = "smart"

[env.production.vars]
RELEASE = ""
LIVEPEER_API_KEY = ""
