name = "groups"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "groups.hey.xyz", custom_domain = true }
]

kv_namespaces = [
  { binding = "GROUPS", id = "4c7d9f98e6124f98a2ef1c523162bf15", preview_id = "4c7d9f98e6124f98a2ef1c523162bf15" }
]

[env.production.vars]
RELEASE = ""
SUPABASE_KEY = ""
